@extends('layouts.app')
@section('title', 'Cek Pesanan — Keripik iLiL')
@section('meta_description', 'Cek status pesanan keripik pisang premium Keripik iLiL Anda via WhatsApp.')

@section('content')
    {{-- Background Gradient (Fixed to allow Parallax Z-Index) --}}
    <div class="bg-root"></div>

    <style>
        :root {
            --chip-1-url: url("{{ asset('assets/chips/chip1.png') }}");
            --chip-2-url: url("{{ asset('assets/chips/chip2.png') }}");
            --chip-3-url: url("{{ asset('assets/chips/chip3.png') }}");
        }
    </style>

    {{-- Cinematic overlays --}}
    <div class="cinema"></div>
    <div class="grain"></div>

    {{-- Fixed parallax background — keripik clusters generated by JS --}}
    <div class="bg-parallax" id="bg"></div>

    {{-- Navbar --}}
    <nav class="nav scrolled">
        <div class="container">
            <div class="nav-inner glass reveal">
                <a class="brand" href="{{ url('/') }}">
                    <img src="{{ asset('assets/brand/logo.png') }}" alt="Keripik iLiL" />
                    <div class="flex flex-col leading-tight">
                        <strong>Keripik iLiL</strong>
                        <span class="text-xs" style="color:var(--muted)">Kembali ke Beranda</span>
                    </div>
                </a>
            </div>
        </div>
    </nav>

    {{-- PAGE CONTENT --}}
    <section class="section" style="padding-top: 110px; min-height: 100vh;">
        <div class="container">
            <div style="max-width: 600px; margin: 0 auto;">
                <div class="order-box glass reveal">
                    <div class="section-title reveal" style="justify-content: center; text-align: center; margin-bottom: 30px;">
                        <div>
                            <h2>Cek Pesanan</h2>
                            <p>Masukkan Nomor WhatsApp Anda untuk melihat status pesanan terakhir.</p>
                        </div>
                    </div>
                    
                    <form action="{{ route('cek-pesanan.search') }}" method="POST" style="margin-bottom: 24px;">
                        @csrf
                        <div class="form-group" style="margin-bottom: 16px;">
                            <label for="wa_number" style="display:block; font-size:.85rem; font-weight:600; color:rgba(255,255,255,.8); margin-bottom:8px;">Nomor WhatsApp *</label>
                            <div style="display:flex; gap:8px;">
                                <input type="tel" id="wa_number" name="wa_number" 
                                    style="flex:1; padding:12px 16px; background:rgba(255,255,255,.05); border:1px solid var(--stroke); border-radius:12px; color:#fff; outline:none; transition:all .2s;"
                                    placeholder="Cth: 081234567890" value="{{ old('wa_number', $waNumber ?? '') }}" required>
                                <button type="submit" class="btn primary" style="padding:12px 24px; font-size:1rem; border-radius:12px;">Cari</button>
                            </div>
                        </div>
                    </form>

                    @if(isset($order))
                        <div style="background:rgba(255,255,255,.05); border:1px solid var(--stroke); border-radius:16px; padding:20px; margin-top:30px;">
                            <div style="display:flex; justify-content:space-between; align-items:center; border-bottom:1px solid rgba(255,255,255,.1); padding-bottom:16px; margin-bottom:16px;">
                                <div>
                                    <div style="font-size:0.85rem; color:var(--muted); margin-bottom:4px;">Nama Pelanggan</div>
                                    <div style="font-weight:600; font-size:1.1rem;">{{ $order->name }}</div>
                                </div>
                                <div style="text-align:right;">
                                    <div style="font-size:0.85rem; color:var(--muted); margin-bottom:4px;">Status</div>
                                    @if($order->status == 'pending')
                                        <span style="background:rgba(234, 179, 8, 0.2); color:#eab308; padding:4px 10px; border-radius:20px; font-size:0.8rem; font-weight:600; border:1px solid rgba(234, 179, 8, 0.4);">Menunggu Proses</span>
                                    @elseif($order->status == 'processed')
                                        <span style="background:rgba(59, 130, 246, 0.2); color:#3b82f6; padding:4px 10px; border-radius:20px; font-size:0.8rem; font-weight:600; border:1px solid rgba(59, 130, 246, 0.4);">Diproses</span>
                                    @elseif($order->status == 'completed')
                                        <span style="background:rgba(34, 197, 94, 0.2); color:#22c55e; padding:4px 10px; border-radius:20px; font-size:0.8rem; font-weight:600; border:1px solid rgba(34, 197, 94, 0.4);">Selesai</span>
                                    @elseif($order->status == 'cancelled')
                                        <span style="background:rgba(239, 68, 68, 0.2); color:#ef4444; padding:4px 10px; border-radius:20px; font-size:0.8rem; font-weight:600; border:1px solid rgba(239, 68, 68, 0.4);">Dibatalkan</span>
                                    @endif
                                </div>
                            </div>

                            <div style="font-size:0.9rem; font-weight:600; margin-bottom:12px; color:rgba(255,255,255,.8);">Detail Produk:</div>
                            <div style="display:flex; flex-direction:column; gap:12px; margin-bottom:20px;">
                                @foreach($order->items as $item)
                                    <div style="display:flex; justify-content:space-between; align-items:center; background:rgba(0,0,0,.2); padding:10px 14px; border-radius:10px;">
                                        <div>
                                            <div style="font-weight:600; font-size:0.95rem;">{{ $item->product->name ?? 'Produk Terhapus' }}</div>
                                            <div style="font-size:0.8rem; color:var(--muted);">{{ $item->quantity }} x Rp {{ number_format($item->price, 0, ',', '.') }}</div>
                                        </div>
                                        <div style="font-weight:600; color:var(--accent);">
                                            Rp {{ number_format($item->subtotal, 0, ',', '.') }}
                                        </div>
                                    </div>
                                @endforeach
                            </div>

                            @if($order->voucher_code)
                                <div style="display:flex; justify-content:space-between; align-items:center; border-top:1px solid rgba(255,255,255,.1); padding-top:16px; margin-bottom:8px;">
                                    <span style="color:var(--muted); font-weight:600;">Subtotal:</span>
                                    <span style="color:#fff;">Rp {{ number_format($order->total_price + $order->discount_amount, 0, ',', '.') }}</span>
                                </div>
                                <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:8px;">
                                    <span style="color:var(--accent); font-weight:600;">Diskon Voucher ({{ $order->voucher_code }}):</span>
                                    <span style="color:var(--accent);">-Rp {{ number_format($order->discount_amount, 0, ',', '.') }}</span>
                                </div>
                                <div style="display:flex; justify-content:space-between; align-items:center; border-top:1px solid rgba(255,255,255,.1); padding-top:12px;">
                                    <span style="color:var(--muted); font-weight:600;">Total Tagihan:</span>
                                    <strong style="font-size:1.3rem; color:var(--accent);">Rp {{ number_format($order->total_price, 0, ',', '.') }}</strong>
                                </div>
                            @else
                                <div style="display:flex; justify-content:space-between; align-items:center; border-top:1px solid rgba(255,255,255,.1); padding-top:16px;">
                                    <span style="color:var(--muted); font-weight:600;">Total Tagihan:</span>
                                    <strong style="font-size:1.3rem; color:var(--accent);">Rp {{ number_format($order->total_price, 0, ',', '.') }}</strong>
                                </div>
                            @endif
                        </div>
                    @endif

                    <div style="margin-top: 24px;">
                        <a href="{{ route('order-page.index') }}" class="btn" style="width:100%; padding:14px; font-size:.95rem; border-radius:12px; display:block; text-align:center; background-color:rgba(255,255,255,0.1); color:#fff; text-decoration: none; border: 1px solid var(--stroke); transition: background 0.2s;" onmouseover="this.style.background='rgba(255,255,255,0.15)'" onmouseout="this.style.background='rgba(255,255,255,0.1)'">
                            ← Kembali ke Form Pemesanan
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {{-- Fat Footer --}}
    <footer class="footer-fat">
        <div class="container py-12">
            <div class="border-t border-white/10 mt-16 pt-8 flex flex-col md:flex-row justify-between items-center gap-4 text-xs text-white/30">
                <p>&copy; {{ date('Y') }} Keripik iLiL. All rights reserved.</p>
                <div class="flex gap-6">
                    <a href="#" class="hover:text-white transition">Privacy Policy</a>
                    <a href="#" class="hover:text-white transition">Terms of Service</a>
                </div>
            </div>
        </div>
    </footer>

    @push('scripts')
    <!-- SweetAlert2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        const swalDarkConfig = {
            color: '#fff',
            backdrop: 'rgba(0,0,0,0.6)',
            allowOutsideClick: false,
            customClass: {
                popup: 'glass',
                confirmButton: 'btn primary'
            },
            confirmButtonColor: 'var(--accent)'
        };

        @if(session('error'))
            Swal.fire({
                ...swalDarkConfig,
                icon: 'error',
                title: 'Tidak Ditemukan',
                text: '{{ session('error') }}',
            });
        @endif
    </script>
    
    {{-- Parallax Background script from landing page (Optimized for Mobile) --}}
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const bg = document.getElementById('bg');
            if (bg) {
                const isMobile = window.innerWidth < 768;
                const count = isMobile ? 5 : 18; // Reduced count for mobile
                
                for(let i=0; i<count; i++){
                    const chip = document.createElement('div');
                    chip.className = `chip chip-${Math.floor(Math.random()*3)+1}`;
                    chip.style.left = `${Math.random()*100}vw`;
                    chip.style.top = `${Math.random()*200}vh`; // spread further down
                    
                    const scale = isMobile ? (0.3 + Math.random()*0.2) : (0.4 + Math.random()*0.4);
                    chip.style.transform = `scale(${scale}) rotate(${Math.random()*360}deg)`;
                    
                    // Filters (blur) are notoriously slow on mobile GPUs. Only apply to desktop.
                    if (isMobile) {
                        chip.style.opacity = `${0.4 + Math.random()*0.3}`;
                    } else {
                        chip.style.filter = `blur(${Math.random()*4}px) opacity(${0.5 + Math.random()*0.4})`;
                    }
                    bg.appendChild(chip);
                }

                let ticking = false;
                window.addEventListener('scroll', () => {
                    const scrolled = window.scrollY;
                    if (!ticking) {
                        window.requestAnimationFrame(() => {
                            bg.style.transform = `translateY(${scrolled * 0.4}px)`;
                            ticking = false;
                        });
                        ticking = true;
                    }
                }, {passive:true});
            }
        });
    </script>
    @endpush
@endsection
