@extends('layouts.app')

@section('title', 'Keripik iLiL — Berani Coba, Berani Ketagihan')
@section('meta_description', 'Keripik pisang premium dari Bandung. Cinematic landing page glassmorphism + parallax + Three.js.')

@section('content')
    {{-- Server-side products data for JS --}}
    <script>window.__PRODUCTS__ = @json($productsJson);</script>

    {{-- Background Gradient (Fixed to allow Parallax Z-Index) --}}
    <div class="bg-root"></div>

    <style>
        :root {
            --chip-1-url: url("{{ asset('assets/chips/chip1.png') }}");
            --chip-2-url: url("{{ asset('assets/chips/chip2.png') }}");
            --chip-3-url: url("{{ asset('assets/chips/chip3.png') }}");
        }
    </style>

    {{-- Cinematic overlays --}}
    <div class="cinema"></div>
    <div class="grain"></div>

    {{-- Fixed parallax background — keripik clusters generated by JS --}}
    <div class="bg-parallax" id="bg"></div>

    {{-- Navbar --}}
    <nav class="nav">
        <div class="container">
            <div class="nav-inner glass reveal">
            <a class="brand" href="#top">
                <img src="{{ asset('assets/brand/logo.png') }}" alt="Keripik iLiL" />
                <div class="flex flex-col leading-tight">
                    <strong>Keripik iLiL</strong>
                    <span class="text-xs" style="color:var(--muted)">Berani Coba, Berani Ketagihan</span>
                </div>
            </a>

            <nav class="nav-links" aria-label="Navigasi">
                <a href="#tentang">Tentang</a>
                <a href="#produk">Produk</a>
                <a href="#galeri">Galeri</a>
                <a href="#tim">Tim</a>
                <a href="#pesan">Pesan</a>
            </nav>

            <div class="nav-actions">
                <div class="cart-pill" id="cartBtn" role="button" aria-label="Buka keranjang">
                    <span class="opacity-90">🛒</span>
                    <span class="font-black">Cart</span>
                    <span class="cart-count" id="cartCount">0</span>
                </div>
                <a class="btn primary" href="#pesan">Order</a>
            </div>
        </div>
    </div>
    </nav>

    {{-- HERO --}}
    <header class="section hero" id="top" style="padding-top: 160px;">
        <div class="container">
            <div class="hero-grid">
                <div class="hero-copy glass reveal" id="heroTilt">
                    <div class="badge"><span class="dot"></span> Asli Bandung • 100% Pisang Pilihan • Tanpa Pengawet</div>

                    <h1>
                        <span style="color:var(--accent)">Berani Coba</span><br/>
                        <span style="color:var(--accent2)">Berani Ketagihan</span>
                    </h1>

                    <p>
                        Keripik pisang tipis renyah dengan bumbu melimpah yang meresap sempurna. Dibuat dari pisang kepok pilihan, digoreng garing, dan disajikan untuk menemani setiap momen santai Anda. Sekali gigit, dijamin susah berhenti!
                    </p>

                    <div class="hero-cta">
                        <a class="btn whatsapp" id="ctaWa" href="#" title="Pesan via WhatsApp">💬 Pesan WhatsApp</a>
                        <a class="btn market" id="ctaMk" href="#" title="Checkout Marketplace">🛍️ Marketplace</a>
                        <button class="btn primary" id="ctaWeb" type="button" title="Checkout via Web">🧾 Checkout Web</button>
                        <a class="btn ghost" href="#produk" title="Lihat varian rasa">🍌 Pilih Rasa</a>
                    </div>

                    <div class="hero-note">
                        <span class="badge">✨ Best Seller: Balado & Coklat Lumer</span>
                        <span class="badge">🔥 Selalu Fresh made by order</span>
                    </div>
                </div>

                <div class="hero-right glass reveal" id="threeTilt" aria-label="Animasi produk utama (real pack)">
                    <div id="threeWrap">
                        <canvas id="three"></canvas>
                    </div>
                    <div class="three-overlay glass" hidden>
                        <small>
                            <b>Produk Utama (Real Pack)</b><br/>
                            Three.js menampilkan foto pack kamu + chip particles.
                        </small>
                        <span class="kbd">SCROLL</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    {{-- MARQUEE TESTIMONIALS --}}
    <div class="container">
        <div class="marquee-wrap" style="-webkit-mask-image: linear-gradient(to right, transparent 0%, black 20%, black 80%, transparent 100%); mask-image: linear-gradient(to right, transparent 0%, black 20%, black 80%, transparent 100%);">
            <div class="marquee">
                @foreach(range(1,10) as $i)
                    <div class="review-card text-sm">
                        <div class="flex gap-1 mb-2 text-yellow-400">★★★★★</div>
                        <p class="mb-2">"Gila sih ini keripiknya tipis banget jadi super renyah. Bumbu baladonya nendang pol, beneran bikin ketagihan!"</p>
                        <small class="text-white/50">— Riska, Jakarta</small>
                    </div>
                    <div class="review-card text-sm">
                        <div class="flex gap-1 mb-2 text-yellow-400">★★★★★</div>
                        <p class="mb-2">"Biasanya beli keripik pisang keras, tapi iLiL empuk renyah. Varian coklatnya the best, lumer tapi ga bikin eneg."</p>
                        <small class="text-white/50">— Aditya, Bandung</small>
                    </div>
                    <div class="review-card text-sm">
                        <div class="flex gap-1 mb-2 text-yellow-400">★★★★★</div>
                        <p class="mb-2">"Packaging rapi, sampe ke Kalimantan aman sentosa ga hancur. Cocok banget buat stok ngemil nonton drakor."</p>
                        <small class="text-white/50">— Siska, Balikpapan</small>
                    </div>
                    <div class="review-card text-sm">
                        <div class="flex gap-1 mb-2 text-yellow-400">★★★★★</div>
                        <p class="mb-2">"Awalnya cuma beli 1 buat iseng nyoba, eh nyesel dong karena langsung abis sehari. Next order langsung borong!"</p>
                        <small class="text-white/50">— Danang, Surabaya</small>
                    </div>
                @endforeach
            </div>
        </div>
    </div>

    {{-- TENTANG --}}
    <section class="section compact" id="tentang">
        <div class="container">
            <div class="section-title reveal">
                <div>
                    <h2>Tentang Keripik iLiL</h2>
                    <p>Cita rasa lokal dengan kualitas premium yang bikin kangen terus.</p>
                </div>
            </div>

            <div class="about-grid">
                <div class="about-copy glass reveal">
                    <p class="m-0 leading-relaxed" style="color:var(--muted)">
                        Berawal dari kecintaan pada camilan kampung halaman, Keripik iLiL hadir untuk menaikkan level keripik pisang tradisional. Kami memotong pisang dengan tingkat ketipisan presisi agar teksturnya ekstra renyah, lalu membalutnya dengan racikan bumbu rahasia yang kaya rasa, tanpa pelit! Kami berkomitmen menyajikan camilan enak yang bikin mood Anda naik seharian.
                    </p>
                </div>

                <div class="about-stats">
                    <div class="stat reveal">
                        <strong>6+</strong>
                        <span>Varian rasa</span>
                    </div>
                    <div class="stat reveal">
                        <strong>Bandung</strong>
                        <span>Asal produksi</span>
                    </div>
                    <div class="stat reveal">
                        <strong>Fresh</strong>
                        <span>Digoreng Tiap Hari</span>
                    </div>
                    <div class="stat reveal">
                        <strong>Premium</strong>
                        <span>Bahan Berkualitas</span>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {{-- PRODUK --}}
    <section class="section" id="produk">
        <div class="container">
            <div class="section-title reveal">
                <div>
                    <h2>Varian Rasa Favorit</h2>
                    <p>Pilih rasa andalanmu. Bumbu tebal, renyah maksimal!</p>
                </div>
                <span class="badge">� Paling Laris: Coklat & Balado</span>
            </div>

            <div class="product-grid" id="productGrid"></div>
        </div>
    </section>

    {{-- GALERI --}}
    <section class="section compact" id="galeri">
        <div class="container">
            <div class="section-title reveal">
                <div>
                    <h2>Galeri</h2>
                    <p>Klik foto untuk cinematic lightbox.</p>
                </div>
            </div>

            <div class="gallery-grid" id="galleryGrid"></div>
        </div>
    </section>

    {{-- TIM --}}
    <section class="section compact" id="tim">
        <div class="container">
            <div class="section-title reveal">
                <div>
                    <h2>Tim Kami</h2>
                    <p>Ganti avatar tim nanti. (Sementara pakai logo/placeholder)</p>
                </div>
            </div>

            <div class="team-grid">
                <div class="person reveal">
                    <div class="avatar"><img src="{{ asset('assets/brand/logo.png') }}" alt="Icha - Founder Keripik iLiL"></div>
                    <div><strong>Icha</strong><span>Founder</span></div>
                </div>
                <div class="person reveal">
                    <div class="avatar"><img src="{{ asset('assets/brand/logo.png') }}" alt="Beno - Tim IT Keripik iLiL"></div>
                    <div><strong>Beno</strong><span>Tim IT</span></div>
                </div>
                <div class="person reveal">
                    <div class="avatar"><img src="{{ asset('assets/brand/logo.png') }}" alt="Mah Jijil - Tim Produksi Keripik iLiL"></div>
                    <div><strong>Mah Jijil</strong><span>Produksi</span></div>
                </div>
                <div class="person reveal">
                    <div class="avatar"><img src="{{ asset('assets/brand/logo.png') }}" alt="Kika - Bagian Umum Keripik iLiL"></div>
                    <div><strong>Kika</strong><span>Umum</span></div>
                </div>
            </div>
        </div>
    </section>

    {{-- PESAN --}}
    <section class="section" id="pesan">
        <div class="container">
            <div class="section-title reveal">
                <div>
                    <h2>Pesan Sekarang!</h2>
                    <p>Jangan nunggu sampai ngiler. Stock cepat habis, amankan keripikmu sekarang.</p>
                </div>
            </div>

            <div class="order-grid">
                <div class="order-box glass reveal">
                    <div class="badge"><span class="dot"></span> Pengiriman ke Seluruh Indonesia</div>
                    <h3 class="mt-2.5 mb-0">Pilih cara beli yang paling nyaman.</h3>
                    <p>
                        Pilih metode pemesanan kesukaan Anda!
                        Mau respons cepat via admin? Klik <b>WhatsApp</b>.<br/>
                        Suka pakai promo gratis ongkir? Kami ada di <b>Marketplace</b>.<br/>
                        Atau mau checkout kilat? Gunakan fitur <b>Keranjang Web</b> kami!
                    </p>

                    <div class="order-actions">
                        <a class="btn whatsapp" id="orderWa" href="#">💬 Pesan via WhatsApp</a>
                        <a class="btn market" id="orderMk" href="#">🛍️ Checkout Marketplace</a>
                        <button class="btn primary" id="orderWeb" type="button">🧾 Checkout di Web</button>
                    </div>

                    <div class="order-mini">
                        <div class="mini-card">
                            <strong>Jam Operasional</strong>
                            <span>09:00–21:00</span>
                        </div>
                        <div class="mini-card">
                            <strong>Lokasi</strong>
                            <span>Bandung, Indonesia</span>
                        </div>
                    </div>
                </div>

                <div class="order-box glass reveal">
                    <h3 class="mt-0 mb-2.5">Info Kontak</h3>
                    <div class="mini-card mb-3">
                        <strong>WhatsApp</strong>
                        <span id="waText">+62 8xx-xxxx-xxxx</span>
                    </div>
                    <div class="mini-card mb-3">
                        <strong>Marketplace</strong>
                        <span>Shopee / Tokopedia</span>
                    </div>
                    <div class="mini-card">
                        <strong>Email</strong>
                        <span>hello@keripikilil.example</span>
                    </div>

                    <p class="mt-3" style="color:var(--muted)">
                        Follow SOSMED kami untuk info promo dadakan dan giveaway bulanan!
                    </p>
                </div>
            </div>
        </div>
    </section>

    {{-- Fat Footer --}}
    <footer class="footer-fat" style="background-color: #08130c;">
        <div class="container py-12">
            <div class="grid grid-cols-1 md:grid-cols-4 gap-10">
                {{-- Brand --}}
                <div class="col-span-1">
                    <div class="flex items-center gap-3 mb-5">
                        <img src="{{ asset('assets/brand/logo.png') }}" alt="Logo Keripik iLiL" class="w-10 h-10 rounded-xl glass p-1"/>
                        <span class="font-bold text-xl tracking-tight text-white">iLiL</span>
                    </div>
                    <p class="text-sm text-white/60 leading-relaxed mb-6">
                        Keripik premium dengan cita rasa otentik yang bikin nagih. Teman setia di setiap momen santai.
                    </p>
                    <div class="flex gap-3">
                        <a href="#" class="social-btn">IG</a>
                        <a href="#" class="social-btn">WA</a>
                        <a href="#" class="social-btn">TT</a>
                        <a href="#" class="social-btn">YT</a>
                    </div>
                </div>

                {{-- Links --}}
                <div>
                    <h4 class="text-white font-bold mb-5 text-sm uppercase tracking-wider">Menu</h4>
                    <ul class="space-y-3 text-sm text-white/60">
                        <li><a href="#tentang" class="hover:text-accent transition duration-300">Tentang Kami</a></li>
                        <li><a href="#produk" class="hover:text-accent transition duration-300">Varian Rasa</a></li>
                        <li><a href="#galeri" class="hover:text-accent transition duration-300">Galeri Foto</a></li>
                        <li><a href="#tim" class="hover:text-accent transition duration-300">Tim Kami</a></li>
                    </ul>
                </div>

                {{-- Contact --}}
                <div>
                    <h4 class="text-white font-bold mb-5 text-sm uppercase tracking-wider">Hubungi</h4>
                    <ul class="space-y-4 text-sm text-white/60">
                        <li class="flex items-start gap-3">
                            <span class="opacity-50">📍</span>
                            <span>Jl. Keripik No. 12<br>Bandung, Jawa Barat</span>
                        </li>
                        <li class="flex items-center gap-3">
                            <span class="opacity-50">📞</span>
                            <span>+62 812 3456 7890</span>
                        </li>
                        <li class="flex items-center gap-3">
                            <span class="opacity-50">✉️</span>
                            <span>halo@keripikilil.com</span>
                        </li>
                    </ul>
                </div>
                
                 {{-- Newsletter --}}
                <div>
                    <h4 class="text-white font-bold mb-5 text-sm uppercase tracking-wider">Update Promo</h4>
                    <p class="text-xs text-white/50 mb-4 leading-relaxed">Dapetin info diskon & varian baru duluan. Tenang, ga spam kok.</p>
                    <form class="flex gap-2">
                        <input type="email" placeholder="Email kamu..." class="glass px-4 py-2.5 rounded-xl text-sm w-full outline-none focus:border-accent border border-white/10 transition placeholder-white/20 bg-transparent text-white">
                        <button type="button" class="btn primary p-2.5 rounded-xl aspect-square flex items-center justify-center">
                            <span>→</span>
                        </button>
                    </form>
                </div>
            </div>

            <div class="border-t border-white/10 mt-16 pt-8 flex flex-col md:flex-row justify-between items-center gap-4 text-xs text-white/30">
                <p>&copy; {{ date('Y') }} Keripik iLiL. All rights reserved.</p>
                <div class="flex gap-6">
                    <a href="#" class="hover:text-white transition">Privacy Policy</a>
                    <a href="#" class="hover:text-white transition">Terms of Service</a>
                </div>
            </div>
        </div>
    </footer>

    {{-- Cart Modal --}}
    <div class="modal" id="modal">
        <div class="modal-panel glass">
            <div class="modal-head">
                <div class="flex items-center gap-2.5">
                    <span class="text-lg">🛒</span>
                    <div>
                        <div class="font-black">Keranjang</div>
                        <div class="text-xs" style="color:var(--muted)">Tambah produk dari section "Varian Rasa".</div>
                    </div>
                </div>
                <button class="btn ghost" id="closeModal" type="button">Tutup</button>
            </div>

            <div class="modal-body">
                <div class="list" id="cartList"></div>

                <div class="summary">
                    <div class="summary-row">
                        <span>Total item</span>
                        <b id="sumItems">0</b>
                    </div>
                    <div class="summary-row">
                        <span>Subtotal</span>
                        <b id="sumSubtotal">Rp 0</b>
                    </div>
                    <div class="summary-row">
                        <span>Ongkir</span>
                        <b style="color:var(--muted)">Nanti</b>
                    </div>

                    <div class="flex gap-2.5 flex-wrap mt-3">
                        <a class="btn whatsapp" id="checkoutWa" href="#">💬 Checkout WA</a>
                        <a class="btn market" id="checkoutMk" href="#">🛍️ Marketplace</a>
                        <button class="btn primary" id="checkoutWeb" type="button">💳 Bayar Online</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{-- Gallery Lightbox --}}
    <div class="lightbox" id="lightbox" aria-hidden="true">
        <div class="lightbox-inner">
            <img id="lightImg" alt="Preview Galeri">
            <div class="lightbox-bar">
                <small id="lightCap">Galeri</small>
                <div class="flex gap-2">
                    <button class="iconbtn" id="prevImg" type="button">‹</button>
                    <button class="iconbtn" id="nextImg" type="button">›</button>
                    <button class="iconbtn" id="closeLight" type="button">✕</button>
                </div>
            </div>
        </div>
    </div>
@endsection
