@extends('layouts.app')
@section('title', 'Pesan Langsung — Keripik iLiL')
@section('meta_description', 'Pesan langsung keripik pisang premium Keripik iLiL via WhatsApp.')

@section('content')
    {{-- Background Gradient (Fixed to allow Parallax Z-Index) --}}
    <div class="bg-root"></div>

    <style>
        :root {
            --chip-1-url: url("{{ asset('assets/chips/chip1.png') }}");
            --chip-2-url: url("{{ asset('assets/chips/chip2.png') }}");
            --chip-3-url: url("{{ asset('assets/chips/chip3.png') }}");
        }
    </style>

    {{-- Cinematic overlays --}}
    <div class="cinema"></div>
    <div class="grain"></div>

    {{-- Fixed parallax background — keripik clusters generated by JS --}}
    <div class="bg-parallax" id="bg"></div>

    {{-- Navbar --}}
    <nav class="nav scrolled">
        <div class="container">
            <div class="nav-inner glass reveal">
                <a class="brand" href="{{ url('/') }}">
                    <img src="{{ asset('assets/brand/logo.png') }}" alt="Keripik iLiL" />
                    <div class="flex flex-col leading-tight">
                        <strong>Keripik iLiL</strong>
                        <span class="text-xs" style="color:var(--muted)">Kembali ke Beranda</span>
                    </div>
                </a>
            </div>
        </div>
    </nav>

    {{-- PAGE CONTENT --}}
    <section class="section" style="padding-top: 110px; min-height: 100vh;">
        <div class="container">
            

            <div style="max-width: 600px; margin: 0 auto;">


                <div class="order-box glass reveal">
                    <div class="section-title reveal" style="justify-content: center; text-align: center; margin-bottom: 20px;">
                        <div>
                            <h2><i class="bi bi-bag-heart-fill"></i> Pesan Langsung</h2>
                            <p>Isi form di bawah ini untuk memesan langsung.</p>
                        </div>
                    </div>
                    <form action="{{ route('order-page.store') }}" method="POST" id="directOrderForm">
                        @csrf
                        
                        <div class="form-group" style="margin-bottom: 16px;">
                            <label for="wa_number" style="display:block; font-size:.85rem; font-weight:600; color:rgba(255,255,255,.8); margin-bottom:8px;">Nomor WhatsApp *</label>
                            <input type="tel" id="wa_number" name="wa_number" 
                                style="width:100%; padding:12px 16px; background:rgba(255,255,255,.05); border:1px solid var(--stroke); border-radius:12px; color:#fff; outline:none; transition:all .2s;"
                                placeholder="Cth: 081234567890" value="{{ old('wa_number') }}" required>
                            <small id="mergeNotification" style="display:none; color:var(--accent); margin-top:8px;">
                                <svg style="width:14px; height:14px; display:inline; vertical-align:text-bottom;" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                                Nomor WhatsApp ini memiliki pesanan aktif. Pesanan baru akan digabungkan.
                            </small>
                        </div>

                        <div class="form-group" style="margin-bottom: 16px;">
                            <label for="name" style="display:block; font-size:.85rem; font-weight:600; color:rgba(255,255,255,.8); margin-bottom:8px;">Nama Lengkap *</label>
                            <input type="text" id="name" name="name" 
                                style="width:100%; padding:12px 16px; background:rgba(255,255,255,.05); border:1px solid var(--stroke); border-radius:12px; color:#fff; outline:none; transition:all .2s;"
                                placeholder="Masukkan nama Anda" value="{{ old('name') }}" required>
                        </div>
                        
                        <div class="form-group" style="margin-bottom: 16px;">
                            <label for="email" style="display:block; font-size:.85rem; font-weight:600; color:rgba(255,255,255,.8); margin-bottom:8px;">Email (Opsional)</label>
                            <input type="email" id="email" name="email" 
                                style="width:100%; padding:12px 16px; background:rgba(255,255,255,.05); border:1px solid var(--stroke); border-radius:12px; color:#fff; outline:none; transition:all .2s;"
                                placeholder="email@example.com" value="{{ old('email') }}">
                        </div>
                        
                        <div class="form-group" style="margin-bottom: 24px;">
                            <label style="display:block; font-size:.85rem; font-weight:600; color:rgba(255,255,255,.8); margin-bottom:12px;">Pesan Produk *</label>
                            <div style="display:flex; flex-direction:column; gap:12px;">
                                @foreach($products as $product)
                                <div style="display:flex; justify-content:space-between; align-items:center; padding:12px; background:rgba(255,255,255,.05); border:1px solid var(--stroke); border-radius:12px;">
                                    <div>
                                        <div style="font-weight:600; color:#fff;">{{ $product->name }}</div>
                                        <div style="font-size:.85rem; color:var(--accent);">{{ $product->formatted_price }}</div>
                                    </div>
                                    <div style="display:flex; align-items:center; gap:8px;">
                                        <button type="button" style="width:32px; height:32px; border-radius:8px; background:rgba(255,255,255,.1); border:1px solid var(--stroke); color:#fff; cursor:pointer; font-weight:bold;" onclick="updateQty({{ $product->id }}, -1)">−</button>
                                        <input type="number" id="qty_{{ $product->id }}" name="products[{{ $product->id }}]" min="0" max="{{ $product->stock ?? 100 }}" value="{{ old('products.'.$product->id, 0) }}" data-price="{{ $product->price }}"
                                            style="width:40px; height:32px; text-align:center; background:transparent; border:none; color:#fff; font-weight:bold; outline:none; -moz-appearance:textfield; appearance:textfield;" class="qty-input" readonly>
                                        <button type="button" style="width:32px; height:32px; border-radius:8px; background:rgba(255,255,255,.1); border:1px solid var(--stroke); color:#fff; cursor:pointer; font-weight:bold;" onclick="updateQty({{ $product->id }}, 1)">+</button>
                                    </div>
                                </div>
                                @endforeach
                            </div>
                            @error('products')
                                <small style="color:var(--danger); display:block; margin-top:8px;">{{ $message }}</small>
                            @enderror
                        </div>

                        <div class="form-group" style="margin-bottom: 16px;">
                            <label for="catatan" style="display:block; font-size:.85rem; font-weight:600; color:rgba(255,255,255,.8); margin-bottom:8px;">Catatan (Opsional)</label>
                            <textarea type="text" id="catatan" name="catatan" 
                                style="width:100%; padding:12px 16px; background:rgba(255,255,255,.05); border:1px solid var(--stroke); border-radius:12px; color:#fff; outline:none; transition:all .2s;"
                                placeholder="catatan">{{ old('catatan') }}</textarea>
                        </div>

                        <div class="form-group" style="margin-bottom: 24px;">
                            <label for="voucher_code" style="display:block; font-size:.85rem; font-weight:600; color:rgba(255,255,255,.8); margin-bottom:8px;">Kode Voucher</label>
                            <div style="display:flex; gap:12px;">
                                <input type="text" id="voucher_code" name="voucher_code" 
                                    style="flex-grow:1; padding:12px 16px; background:rgba(255,255,255,.05); border:1px solid var(--stroke); border-radius:12px; color:#fff; outline:none; transition:all .2s; text-transform:uppercase;"
                                    placeholder="Masukkan kode voucher" value="{{ old('voucher_code') }}">
                                <button type="button" id="applyVoucherBtn" class="btn primary" style="padding:0 24px; border-radius:12px;"><i class="bi bi-bookmark-star-fill" style="font-size:1.5rem;"></i></button>
                            </div>
                            <small id="voucherMessage" style="display:none; margin-top:8px;"></small>
                        </div>

                        <div style="padding-top:20px; border-top:1px solid var(--stroke); margin-bottom:24px; display:flex; flex-direction:column; gap:8px;">
                            <div id="discountRow" style="display:none; justify-content:space-between; align-items:center;">
                                <span style="font-size:.9rem; color:var(--accent);">Diskon Voucher:</span>
                                <strong id="displayDiscount" style="font-size:1.1rem; color:var(--accent);">-Rp 0</strong>
                            </div>
                            <div style="display:flex; justify-content:space-between; align-items:center; margin-top:8px;">
                                <span style="font-size:1.1rem; font-weight:600; color:var(--muted);">Total Pesanan:</span>
                                <div style="display:flex; align-items:center; gap:8px;">
                                    <span id="displayOriginalTotal" style="font-size:1.1rem; color:var(--muted); text-decoration:line-through; display:none;">Rp 0</span>
                                    <strong id="displayTotal" style="font-size:1.6rem; color:var(--accent);">Rp 0</strong>
                                </div>
                            </div>
                        </div>

                        <button type="submit" class="btn primary" style="width:100%; padding:16px; font-size:1rem; border-radius:14px; margin-bottom:12px; display:flex; justify-content:center; align-items:center; gap:8px;">
                            <i class="bi bi-send-check" style="font-size:1.1rem;"></i> Kirim Pesanan
                        </button>
                        
                        <a href="{{ route('cek-pesanan.index') }}" class="btn" style="width:100%; padding:16px; font-size:1rem; border-radius:14px; display:flex; justify-content:center; align-items:center; gap:8px; background-color: var(--accent); color: #000; font-weight: 600; text-decoration: none; border: none; transition: opacity 0.2s;" onmouseover="this.style.opacity='0.9'" onmouseout="this.style.opacity='1'">
                            <i class="bi bi-cart-check" style="font-size:1.1rem;"></i> Cek Pesanan Saya
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </section>

    {{-- Fat Footer --}}
    <footer class="footer-fat">
        <div class="container py-12">
            <div class="border-t border-white/10 mt-16 pt-8 flex flex-col md:flex-row justify-between items-center gap-4 text-xs text-white/30">
                <p>&copy; {{ date('Y') }} Keripik iLiL. All rights reserved.</p>
                <div class="flex gap-6">
                    <a href="#" class="hover:text-white transition">Privacy Policy</a>
                    <a href="#" class="hover:text-white transition">Terms of Service</a>
                </div>
            </div>
        </div>
    </footer>

    @push('scripts')
    <!-- SweetAlert2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        const swalDarkConfig = {
            color: '#fff',
            backdrop: 'rgba(0,0,0,0.6)',
            allowOutsideClick: false,
            customClass: {
                popup: 'glass',
                confirmButton: 'btn primary'
            },
            confirmButtonColor: 'var(--accent)'
        };

        @if(session('success'))
            Swal.fire({
                ...swalDarkConfig,
                icon: 'success',
                title: 'Berhasil!',
                text: '{{ session('success') }}',
            });
        @endif

        @if($errors->any())
            Swal.fire({
                ...swalDarkConfig,
                icon: 'error',
                title: 'Gagal Memproses Pesanan',
                html: `
                    <ul style="text-align: left; margin-top: 10px; color: var(--danger);">
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                `
            });
        @endif
    </script>
    <script>
        const formatRupiah = (number) => {
            return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(number);
        };

        const displayOriginalTotal = document.getElementById('displayOriginalTotal');
        const displayDiscount = document.getElementById('displayDiscount');
        const displayTotal = document.getElementById('displayTotal');
        const discountRow = document.getElementById('discountRow');
        const qtyInputs = document.querySelectorAll('.qty-input');
        
        let currentSubtotal = 0;
        let currentDiscount = 0;

        function calculateTotal() {
            currentSubtotal = 0;
            qtyInputs.forEach(input => {
                const price = parseFloat(input.getAttribute('data-price')) || 0;
                const qty = parseInt(input.value) || 0;
                currentSubtotal += price * qty;
            });
            
            // Re-validate voucher if amount drops below min_purchase? Simplest is to just cap discount.
            let activeDiscount = currentSubtotal > 0 ? currentDiscount : 0;
            // Prevent negative total
            if (activeDiscount > currentSubtotal) activeDiscount = currentSubtotal;

            const finalTotal = currentSubtotal - activeDiscount;

            displayTotal.textContent = formatRupiah(finalTotal);
            
            if (activeDiscount > 0) {
                displayOriginalTotal.textContent = formatRupiah(currentSubtotal);
                displayOriginalTotal.style.display = 'inline';
                displayDiscount.textContent = '-' + formatRupiah(activeDiscount);
                discountRow.style.display = 'flex';
                displayTotal.style.color = '#fff'; // Highlight new total
            } else {
                displayOriginalTotal.style.display = 'none';
                discountRow.style.display = 'none';
                displayTotal.style.color = 'var(--accent)';
            }
        }

        function updateQty(id, change) {
            const input = document.getElementById('qty_' + id);
            let currentQty = parseInt(input.value) || 0;
            const maxQty = parseInt(input.getAttribute('max')) || 100;

            currentQty += change;
            if (currentQty < 0) currentQty = 0;
            
            if (currentQty > maxQty) {
                currentQty = maxQty;
                Swal.fire({
                    ...swalDarkConfig,
                    icon: 'warning',
                    title: 'Stok Habis',
                    text: 'Stok produk ini hanya tersisa ' + maxQty + ' pcs.',
                });
            }

            input.value = currentQty;
            calculateTotal();
        }

        // Setup inputs style event listeners
        document.querySelectorAll('input:not([type="hidden"]):not([readonly]), select').forEach(el => {
            el.addEventListener('focus', () => {
                el.style.borderColor = 'var(--accent)';
                el.style.boxShadow = '0 0 0 3px rgba(57, 217, 138, 0.1)';
            });
            el.addEventListener('blur', () => {
                el.style.borderColor = 'var(--stroke)';
                el.style.boxShadow = 'none';
            });
        });

        // Initialize total on load
        calculateTotal();

        // Check WA Number for auto-complete
        const waInput = document.getElementById('wa_number');
        const nameInput = document.getElementById('name');
        const emailInput = document.getElementById('email');
        const mergeNotification = document.getElementById('mergeNotification');
        
        waInput.addEventListener('blur', function() {
            const waNumber = this.value.trim();
            if (waNumber.length > 5) { // Basic length check
                fetch(`/api/check-wa?wa_number=${encodeURIComponent(waNumber)}`)
                    .then(response => response.json())
                    .then(data => {
                        if (data.exists) {
                            if (!nameInput.value) nameInput.value = data.name;
                            if (!emailInput.value && data.email) emailInput.value = data.email;
                            mergeNotification.style.display = 'block';
                        } else {
                            mergeNotification.style.display = 'none';
                        }
                    })
                    .catch(e => console.error('Error checking WA:', e));
            } else {
                mergeNotification.style.display = 'none';
            }
        });

        // Voucher logic
        const applyVoucherBtn = document.getElementById('applyVoucherBtn');
        const voucherInput = document.getElementById('voucher_code');
        const voucherMessage = document.getElementById('voucherMessage');

        applyVoucherBtn.addEventListener('click', function() {
            const code = voucherInput.value.trim().toUpperCase();
            if(!code) return;

            // Optional: require at least 1 item to be selected before applying voucher
            if(currentSubtotal <= 0) {
                voucherMessage.style.display = 'block';
                voucherMessage.style.color = 'var(--danger)';
                voucherMessage.textContent = 'Silakan pilih produk terlebih dahulu.';
                return;
            }

            // Disable button during req
            applyVoucherBtn.disabled = true;
            applyVoucherBtn.textContent = '...';
            applyVoucherBtn.style.opacity = '0.7';

            fetch('{{ route('api.check-voucher') }}', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                },
                body: JSON.stringify({
                    voucher_code: code,
                    subtotal: currentSubtotal
                })
            })
            .then(res => res.json())
            .then(data => {
                console.log('Voucher Check Response:', data);
                voucherMessage.style.display = 'block';
                if(data.valid) {
                    voucherMessage.style.color = 'var(--accent)';
                    voucherMessage.textContent = data.message;
                    currentDiscount = parseFloat(data.discount) || 0;
                    calculateTotal();
                } else {
                    voucherMessage.style.color = 'var(--danger)';
                    voucherMessage.textContent = data.message;
                    currentDiscount = 0;
                    calculateTotal();
                }
            })
            .catch(err => {
                console.error(err);
                voucherMessage.style.display = 'block';
                voucherMessage.style.color = 'var(--danger)';
                voucherMessage.textContent = 'Terjadi kesalahan sistem saat mengecek voucher.';
                currentDiscount = 0;
                calculateTotal();
            })
            .finally(() => {
                applyVoucherBtn.disabled = false;
                applyVoucherBtn.textContent = 'Terapkan';
                applyVoucherBtn.style.opacity = '1';
            });
        });
    </script>
    
    {{-- Parallax Background script is globally handled by app.js --}}
    @endpush
@endsection
